//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarRelayControl.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarRelayControl.Client.Resources.WebStrings", typeof(WebStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Settings.
        /// </summary>
        internal static string BaseSettingsLabel {
            get {
                return ResourceManager.GetString("BaseSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Power.
        /// </summary>
        internal static string CumulativePower {
            get {
                return ResourceManager.GetString("CumulativePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Power.
        /// </summary>
        internal static string CurrentPowerLabel {
            get {
                return ResourceManager.GetString("CurrentPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dongle IP.
        /// </summary>
        internal static string DongleIpLabel {
            get {
                return ResourceManager.GetString("DongleIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dongle Modbus TCP Port.
        /// </summary>
        internal static string DonglePortLabel {
            get {
                return ResourceManager.GetString("DonglePortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string InstalledLabel {
            get {
                return ResourceManager.GetString("InstalledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter.
        /// </summary>
        internal static string InverterLabel {
            get {
                return ResourceManager.GetString("InverterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter Settings.
        /// </summary>
        internal static string InverterSettingsLabel {
            get {
                return ResourceManager.GetString("InverterSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal PV Output in kW.
        /// </summary>
        internal static string MinPowerLabel {
            get {
                return ResourceManager.GetString("MinPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal SOC in %.
        /// </summary>
        internal static string MinSOCLabel {
            get {
                return ResourceManager.GetString("MinSOCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus ID.
        /// </summary>
        internal static string ModbusIdLabel {
            get {
                return ResourceManager.GetString("ModbusIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Output.
        /// </summary>
        internal static string PVPowerLabel {
            get {
                return ResourceManager.GetString("PVPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay IP.
        /// </summary>
        internal static string RelayIpLabel {
            get {
                return ResourceManager.GetString("RelayIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Settings.
        /// </summary>
        internal static string RelaySettingsLabel {
            get {
                return ResourceManager.GetString("RelaySettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Status.
        /// </summary>
        internal static string RelayStatusLabel {
            get {
                return ResourceManager.GetString("RelayStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Temperature.
        /// </summary>
        internal static string RelayTemperature {
            get {
                return ResourceManager.GetString("RelayTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOC.
        /// </summary>
        internal static string SOCLabel {
            get {
                return ResourceManager.GetString("SOCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string TimestampLabel {
            get {
                return ResourceManager.GetString("TimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Relay Control.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        internal static string TurnOffLabel {
            get {
                return ResourceManager.GetString("TurnOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string TurnOnLabel {
            get {
                return ResourceManager.GetString("TurnOnLabel", resourceCulture);
            }
        }
    }
}
